model:
  type: ResidualVQAutoEncoder
  token_dim: 64
  encoder_depth: 4
  decoder_depth: 4
  num_heads: 8
  num_embeddings: 1024
  bottleneck : residual-vae


super_parameters:
  epochs: 200
  vq_beta: 1.0
  batch_size: 256
  learning_rate: 0.0001
  weight_decay: 0.00001

train:
  save_folder: ./pretrained/roomautoencoders/