model:
  type: ResidualAutoEncoder
  token_dim: 64
  encoder_depth: 4
  decoder_depth: 4
  num_heads: 8
  num_embeddings: 512
  bottleneck : residual-vae


super_parameters:
  epochs: 200
  batch_size: 64
  learning_rate: 0.0001
  weight_decay: 0.00001

train:
  save_folder: ./pretrained/roomautoencoders/